default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: ваш_пользователь  # если не используете DATABASE_URL
  # password: ваш_пароль        # если не используете DATABASE_URL
  # host: localhost             # если база локальная

development:
  <<: *default
  database: tic_tac_toe_app_development

test:
  <<: *default
  database: tic_tac_toe_app_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
