default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: ваш_пользователь  # можно указать, если не используете DATABASE_URL
  # password: ваш_пароль        # можно указать, если не используете DATABASE_URL
  # host: localhost             # если база локальная

development:
  <<: *default
  database: tic_tac_toe_app_development

test:
  <<: *default
  database: tic_tac_toe_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
